### ISSUE TITLE
link to maptile review

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-datitrentinoit#18]
We need to fix/restore the maptile background. To check if this is needed also for some resources preview (like the CSV ones). An update of the ckanext-spatial to the latest vesion should fixes.

Some reference link below:

1) http://dati.trentino.it/dataset

2) http://dati.trentino.it/dataset/tasso-standardizzato-di-mortalita-per-tumore-per-le-persone-di-20-64-anni-maschi1/resource/be124cd7-5f1f-4191-b69a-7649bf5b5a77

3) http://dati.retecivica.bz.it/it/dataset/catalogo-beni-culturali/resource/4c992c3e-b378-4595-974c-d020e3c42f65

**Comment by cezio** [comment]
I've checked spatial extension, it seems preview functionality was removed in master, and moved to https://github.com/ckan/ckanext-geoview

**Comment by tdipisa** [comment]
At this stage we can consider to check the first ckanext-spatial version that implements the fix for mapquest tiles. Then we should test for sure the CSW harvesting using the URL below:

http://www.territorio.provincia.tn.it/geoportlet/srv/eng/csw

using the configuration reported [here](https://github.com/geosolutions-it/ckanext-datitrentinoit/tree/dcatapit#csw-harvest-configuration) in the readme

Below a screenshot with the remainng config:

![Clipboard02.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5943f6b8abdc49001a6611c9/125516c66e82c728ace21e0d46cb989333808ca89dedef11e611b2843b492d762a10e17132d0e27dea477f5759574dac490c5644fcff8829f7e56824db4e17ff933c0120996048e6edc00db513bb27814e80b7ba824bc3ed3a22e28f8a5d73.png)

**Comment by tdipisa** [comment]
Two modifications are required:

1) **Fix for the search map**: use the ckanext-spatial at the revision [44f05e181c4c70e3b062fec49e0f2251b52610a1](https://github.com/ckan/ckanext-spatial/tree/44f05e181c4c70e3b062fec49e0f2251b52610a1) that's direclty subsequent to the one installed for the client that is d946df0eb444f15922e01959d39789ab8cc83bf2

2) **Recline map preview for CVS files**: to solve the [MapQuest Tile issue](https://github.com/ckan/ckan/issues/3162) here we need to update the recline.js file of the Ckan's recline preview. The client has ckan 2.5.2 and the fix has been  released within the 2.5.3, so the replacement of the file with the [fixed version](https://raw.githubusercontent.com/ckan/ckan/ckan-2.5.3/ckanext/reclineview/theme/public/vendor/recline/recline.js) works fine. We just need to consider a possible Ckan's update.
