### ISSUE TITLE
CSW Harvester Update

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-datitrentinoit#27]
We need also to update the CSW harvester of Informatica Trentina (to test using the CSW url specified in [development VM](http://opendata-trento.geo-solutions.it/harvest)):
https://github.com/geosolutions-it/ckanext-datitrentinoit/blob/dcatapit/ckanext/datitrentinoit/harvesters/csw_tn.py

The harvester is quite similar to the one provided in the ckanext-dcatapit, but also extend the [GeoNetwork Harvester](https://github.com/geosolutions-it/ckanext-geonetwork/blob/master/ckanext/geonetwork/harvesters/geonetwork.py)(to map metadata topic category to ckan group)  and the [Multilang Harvester](https://github.com/geosolutions-it/ckanext-multilang/blob/master/ckanext/multilang/harvesters/multilang.py) (to get localized values titles and descriptions)

Since we provided a new schema structure for some dcatapit schema fields (introducing for example the multiple cardinality) we need to align these CSW harvester accordingly.

**Comment by cezio** [comment]
This is still in progress. I've encountered several problems not related to this task so far. Here's list: https://docs.google.com/document/d/15-xNKFZnvJeMBZRRB_SScsWtpNkC6wT1osSryatJ5-k/edit?usp=sharing
