### ISSUE TITLE
Improve/fix migration to new dcatapit

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-datitrentinoit#35]
Upgrade of dcatapit extension and tests performed on [INFO-TN demo instance](http://opendata-trento.geo-solutions.it)

**The client has provided an updated dump of his CKAN's DB that I used for my tests in GeoSolutions demo server**.

- [x] The migration procedure seems to have been interrupted. From command line the execution finished as following:

```
...

2018-09-27 18:55:04,767 INFO  [ckanext.multilang.plugin] :::::::::::: Localized fields are missing in package_multilang table, persisting defaults using values in the table group :::::::::::::::
2018-09-27 18:55:05,424 INFO  [ckanext.multilang.plugin] :::::::::::: Localized fields are missing in package_multilang table, persisting defaults using values in the table group :::::::::::::::
2018-09-27 18:55:06,079 INFO  [ckanext.multilang.plugin] :::::::::::: Localized fields are missing in package_multilang table, persisting defaults using values in the table group :::::::::::::::
2018-09-27 18:55:06,962 INFO  [ckanext.multilang.plugin] :::::::::::: Localized fields are missing in package_multilang table, persisting defaults using values in the table group :::::::::::::::
2018-09-27 18:55:07,357 INFO  [ckanext.multilang.plugin] :::::::::::: Localized fields are missing in package_multilang table, persisting defaults using values in the table group :::::::::::::::
2018-09-27 19:09:07,269 INFO  [ckanext.datastore.db] Making resource u'b006bdeb-472a-4061-9d25-fb43384d5d18' public
2018-09-27 19:09:07,278 INFO  [ckanext.datastore.db] Making resource u'fc5b2f53-e255-4713-af7c-a22000f17ae5' public
2018-09-27 19:09:07,323 INFO  [ckanext.datastore.db] Making resource u'deeae2a9-9268-4b39-9ab1-ab0309bc9d41' public
2018-09-27 19:09:07,386 INFO  [ckanext.datastore.db] Making resource u'13ce9af0-c77d-47f4-ad49-74f0462c092f' public
2018-09-27 19:09:07,395 INFO  [ckanext.datastore.db] Making resource u'd1d854ef-2e0f-4492-ae89-8c049b9613af' public
2018-09-27 19:09:07,404 INFO  [ckanext.datastore.db] Making resource u'f48128af-5dd3-4969-8941-763bf92a4746' public
2018-09-27 19:09:07,414 INFO  [ckanext.datastore.db] Making resource u'a8e13b6b-f29c-4181-ab33-a059cd40b7bd' public
2018-09-27 19:09:07,445 INFO  [ckanext.datastore.db] Making resource u'f70f0452-8112-4ba0-b10e-d478c471e36d' public
2018-09-27 19:20:27,730 INFO  [ckanext.datastore.db] Making resource u'3516d2c7-4517-4f37-909e-e82ab757148c' public
2018-09-27 19:20:27,743 INFO  [ckanext.datastore.db] Making resource u'aece30a7-b134-464d-9e91-c1cfa6c75657' public
2018-09-27 19:20:27,753 INFO  [ckanext.datastore.db] Making resource u'f58da312-9d43-48da-9e9b-4af0e7a1e58f' public
2018-09-27 19:20:27,766 INFO  [ckanext.datastore.db] Making resource u'f680998d-128a-44f1-ab8f-655b0446729c' public
2018-09-27 19:20:27,781 INFO  [ckanext.datastore.db] Making resource u'45610f40-a821-4875-a984-23b45c1440b6' public
2018-09-27 19:20:27,794 INFO  [ckanext.datastore.db] Making resource u'c27e34cc-3478-448d-8a3a-e4a6190ffebc' public
2018-09-27 19:20:41,406 INFO  [ckanext.datastore.db] Making resource u'76db0001-b9d8-428d-969f-ff5be3d3ca7d' public
2018-09-27 19:20:41,420 INFO  [ckanext.datastore.db] Making resource u'75b9c5e6-00be-4f63-b152-b4b3844f854c' public
Traceback (most recent call last):
  File "/usr/local/app_loc/geosolutions/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/local/data_loc/src/ckanext-dcatapit/ckanext/dcatapit/commands/dcatapit.py", line 138, in command
    self.migrate_data()
  File "/usr/local/data_loc/src/ckanext-dcatapit/ckanext/dcatapit/commands/dcatapit.py", line 152, in migrate_data
    do_migrate_data()
  File "/usr/local/data_loc/src/ckanext-dcatapit/ckanext/dcatapit/commands/dcatapit.py", line 407, in do_migrate_data
    update_temporal_coverage(pdata)
  File "/usr/local/data_loc/src/ckanext-dcatapit/ckanext/dcatapit/commands/dcatapit.py", line 557, in update_temporal_coverage
    tend = validators.parse_date(tend).strftime(DATE_FORMAT)
ValueError: year=206 is before 1900; the datetime strftime() methods require year >= 1900
You have mail in /var/spool/mail/geosolutions
(geosolutions) [geosolutions@opendata-trento data_loc]$
```

In the migration log file I found **235** of the following logs, that's ok since the organizations are 235 in this catalog:

*org: [agenzia-del-lavoro-pat] Agenzia del Lavoro - PAT : setting temporal identifier: tmp_ipa_code_1*

but I counted only **1239** occurrences of the word *updating* (the total number of dataset is 6230), so I suspect that the migration was interrupted by the error above without migrating all the datasets. This seems true since the following dataset does not seems to be updated at all:

http://opendata-trento.geo-solutions.it/dataset/comune-di-trento-rendiconto-del-2003

**I think that we need to improve the migration process by adding a log that indicates how many ORGs and DATASETs have been effectively updated as expected**

**If the migration procedure stop working without updating all the datasets in the catalog, a log should be thrown, something like the following:**

*The migration was terminated without updating all the datasets (1239/6230), the error is ...*

- [x] There were errors in updating the *conforms to*. 

Check the following dataset:

http://opendata-trento.geo-solutions.it/dataset/cessazioni-dal-lavoro-anno-2016

The original one from the client's production istance is:

https://dati.trentino.it/dataset/cessazioni-dal-lavoro-anno-2016

**Comment by cezio** [comment]
* Some exceptions weren't catched. This should be fixed now, I also added handling of situation when some values are already present in dataset (like conforms_to). 
This might happen when dataset was harvested from ckan+new dcatapit instance, so values would be in new form already. 

* I've also improved organization identifier saving. Internal workflow for organization update was running update for each package in organization after change, which was very slow for large databases. This also caused duplicated package update.

* each org and package will have line counter lines:
> processing $current_org_counter/$total_organizations organization: $name
> processing $current_package_counter/$total_packages package: $title

 * at the end of processing there will be summary:

> processed 234 out of 235 organizations
processed 98 out of 6245 packages in total
Following 2 datasets failed:
 curve-di-livello-passo-200-m-lineari at position 85: <class 'ckan.logic.ValidationError'>u"'identifier'"
 curve-di-livello-passo-200-m-lineari1 at position 86: <class 'ckan.logic.ValidationError'>u"'identifier'"

There's one hack in displaying those lines - some errors have `__str__()`/`__unicode__()` methods overriden, and will raise exceptions there (which is pretty dumb idea). To avoid that i have to use alternative methods to get error message. 

* I've added few cli switches to the command to allow partial data processing:
 * `-o`/`--offset` - start processing from given packages count offset
 * `-l`/`--limit` - limit processing to given amount of packages
 * `-s`/`--skip-orgs` - do not process organizations, just packages

Related PR: https://github.com/geosolutions-it/ckanext-dcatapit/pull/232

**Comment by tdipisa** [comment]
@cezio

reviewed the PR and it seems ok. Below some feedbacks for other stuff I noticed:

1. When trying to update several (not all) migrated datasets

IntegrityError: (IntegrityError) null value in column "text" violates not-null constraint
DETAIL:  Failing row contains (20721, c55d8733-9ed8-408a-9c16-a3a2bce90e47, creator_name, extra, it, null).
 'UPDATE package_multilang SET text=%(text)s WHERE package_multilang.id = %(package_multilang_id)s' {'text': None, 'package_multilang_id': 20721}
 
2. Different time formats in dataset read
http://opendata-trento.geo-solutions.it/dataset/elenco-beneficiari-taa

**Comment by cezio** [comment]
> When trying to update several (not all) migrated datasets

This seems to be bug in ckanext-multilang: https://github.com/geosolutions-it/ckanext-multilang/pull/20

**Comment by cezio** [comment]
> Different time formats in dataset read
http://opendata-trento.geo-solutions.it/dataset/elenco-beneficiari-taa

This is a bit more complicated, because bad field formats are not visible in edit form too due to parse errors:

![image](https://user-images.githubusercontent.com/116021/46366318-07dcfb80-c67b-11e8-9144-ff8552186159.png)

and saving is blocked too:

![image](https://user-images.githubusercontent.com/116021/46366380-2d6a0500-c67b-11e8-9f27-d5db1b697209.png)

**Comment by cezio** [comment]
> Different time formats in dataset read
http://opendata-trento.geo-solutions.it/dataset/elenco-beneficiari-taa

This should fix this: https://github.com/geosolutions-it/ckanext-dcatapit/pull/234

**Comment by tdipisa** [comment]
@cezio,

it seems ok but see the following dataset:

http://opendata-trento.geo-solutions.it/dataset/elenco-giudici-di-pace

the temporal coverage end date has a different format

**Comment by tdipisa** [comment]
@cezio,

when I try to open in edit some dataset, for example the followings
http://opendata-trento.geo-solutions.it/dataset/edit/variazione-della-popolazione
http://opendata-trento.geo-solutions.it/dataset/edit/variazione-del-pil-in-ppa
http://opendata-trento.geo-solutions.it/dataset/edit/veicoli-totali-con-tassa-di-proprieta-pagata

the following error occurs, and I have a server error:

Error - <type 'exceptions.TypeError'>: must be string, not Undefined
URL: http://localhost:5000/dataset/edit/variazione-della-popolazione
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/weberror/errormiddleware.py', line 171 in __call__
  app_iter = self.application(environ, sr_checker)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/fanstatic/publisher.py', line 234 in __call__
  return request.get_response(self.app)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
  response = request.get_response(self.app)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/local/data_loc/src/ckan/ckan/config/middleware.py', line 389 in inner
  result = application(environ, start_response)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/beaker/middleware.py', line 73 in __call__
  return self.app(environ, start_response)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/beaker/middleware.py', line 155 in __call__
  return self.wrap_app(environ, session_start_response)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/routes/middleware.py', line 131 in __call__
  response = self.app(environ, start_response)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in __call__
  response = self.dispatch(controller, environ, start_response)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch
  return controller(environ, start_response)
File '/usr/local/data_loc/src/ckan/ckan/lib/base.py', line 337 in __call__
  res = WSGIController.__call__(self, environ, start_response)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/pylons/controllers/core.py', line 221 in __call__
  response = self._dispatch_call()
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/pylons/controllers/core.py', line 172 in _dispatch_call
  response = self._inspect_call(func)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call
  result = self._perform_call(func, args)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call
  return func(**args)
File '/usr/local/data_loc/src/ckan/ckan/controllers/package.py', line 813 in edit
  'dataset_type': package_type})
File '/usr/local/data_loc/src/ckan/ckan/lib/base.py', line 216 in render
  loader_class=loader_class)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
  return render_func()
File '/usr/local/data_loc/src/ckan/ckan/lib/base.py', line 154 in render_template
  return render_jinja2(template_name, globs)
File '/usr/local/data_loc/src/ckan/ckan/lib/base.py', line 104 in render_jinja2
  return template.render(**extra_vars)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/jinja2/environment.py', line 894 in render
  return self.environment.handle_exception(exc_info, True)
File '/usr/local/data_loc/src/ckanext-dcatapit/ckanext/dcatapit/templates/package/dcatapit_edit.html', line 1 in top-level template code
  {% extends "package/edit.html" %}
File '/usr/local/data_loc/src/ckan/ckan/templates/package/edit.html', line 1 in top-level template code
  {% extends 'package/edit_base.html' %}
File '/usr/local/data_loc/src/ckanext-multilang/ckanext/multilang/templates/package/edit_base.html', line 5 in top-level template code
  {% set pkg_dict = data %}
File '/usr/local/data_loc/src/ckan/ckan/templates/package/edit_base.html', line 4 in top-level template code
  {% set pkg_dict = c.pkg_dict %}
File '/usr/local/data_loc/src/ckan/ckan/templates/package/base.html', line 3 in top-level template code
  {% set pkg = c.pkg_dict or pkg_dict %}
File '/usr/local/data_loc/src/ckan/ckan/templates/page.html', line 1 in top-level template code
  {% extends "base.html" %}
File '/usr/local/data_loc/src/ckanext-harvest/ckanext/harvest/templates/base.html', line 1 in top-level template code
  {% ckan_extends %}
File '/usr/local/data_loc/src/ckanext-multilang/ckanext/multilang/templates/base.html', line 1 in top-level template code
  {% ckan_extends %}
File '/usr/local/data_loc/src/ckanext-datitrentinoit/ckanext/datitrentinoit/templates/base.html', line 1 in top-level template code
  {% ckan_extends %}
File '/usr/local/data_loc/src/ckanext-geoview/ckanext/geoview/templates/base.html', line 1 in top-level template code
  {% ckan_extends %}
File '/usr/local/data_loc/src/ckan/ckan/templates/base.html', line 103 in top-level template code
  {%- block page %}{% endblock -%}
File '/usr/local/data_loc/src/ckan/ckan/templates/page.html', line 19 in block "page"
  {%- block content %}
File '/usr/local/data_loc/src/ckan/ckan/templates/page.html', line 22 in block "content"
  {% block main_content %}
File '/usr/local/data_loc/src/ckan/ckan/templates/page.html', line 57 in block "main_content"
  {% block primary %}
File '/usr/local/data_loc/src/ckan/ckan/templates/page.html', line 70 in block "primary"
  {% block primary_content %}
File '/usr/local/data_loc/src/ckan/ckan/templates/page.html', line 90 in block "primary_content"
  {% block primary_content_inner %}
File '/usr/local/data_loc/src/ckan/ckan/templates/package/edit.html', line 4 in block "primary_content_inner"
  {% block form %}
File '/usr/local/data_loc/src/ckan/ckan/templates/package/edit.html', line 8 in block "form"
  {{- h.snippet(form_snippet, c=c, **form_vars) -}}
File '/usr/local/data_loc/src/ckan/ckan/lib/helpers.py', line 1277 in snippet
  return base.render_snippet(template_name, **kw)
File '/usr/local/data_loc/src/ckan/ckan/lib/base.py', line 79 in render_snippet
  renderer='snippet')
File '/usr/local/data_loc/src/ckan/ckan/lib/base.py', line 216 in render
  loader_class=loader_class)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
  return render_func()
File '/usr/local/data_loc/src/ckan/ckan/lib/base.py', line 154 in render_template
  return render_jinja2(template_name, globs)
File '/usr/local/data_loc/src/ckan/ckan/lib/base.py', line 104 in render_jinja2
  return template.render(**extra_vars)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/jinja2/environment.py', line 894 in render
  return self.environment.handle_exception(exc_info, True)
File '/usr/local/data_loc/src/ckan/ckan/templates/package/new_package_form.html', line 3 in top-level template code
  {% set form_style = c.form_style or c.action %}
File '/usr/local/data_loc/src/ckanext-multilang/ckanext/multilang/templates/package/snippets/package_form.html', line 3 in top-level template code
  {% set data = h.get_localized_pkg(data)%}
File '/usr/local/data_loc/src/ckan/ckan/templates/package/snippets/package_form.html', line 16 in top-level template code
  {% block basic_fields %}
File '/usr/local/data_loc/src/ckan/ckan/templates/package/snippets/package_form.html', line 17 in block "basic_fields"
  {% snippet 'package/snippets/package_basic_fields.html', data=data, errors=errors, licenses=c.licenses, groups_available=c.groups_available %}
File '/usr/local/data_loc/src/ckan/ckan/lib/jinja_extensions.py', line 255 in _call
  return base.render_snippet(args[0], **kwargs)
File '/usr/local/data_loc/src/ckan/ckan/lib/base.py', line 79 in render_snippet
  renderer='snippet')
File '/usr/local/data_loc/src/ckan/ckan/lib/base.py', line 216 in render
  loader_class=loader_class)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
  return render_func()
File '/usr/local/data_loc/src/ckan/ckan/lib/base.py', line 154 in render_template
  return render_jinja2(template_name, globs)
File '/usr/local/data_loc/src/ckan/ckan/lib/base.py', line 104 in render_jinja2
  return template.render(**extra_vars)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/jinja2/environment.py', line 894 in render
  return self.environment.handle_exception(exc_info, True)
File '/usr/local/data_loc/src/ckanext-multilang/ckanext/multilang/templates/package/snippets/package_basic_fields.html', line 3 in top-level template code
  {% import 'macros/form_macros.html' as form_macros %}
File '/usr/local/data_loc/src/ckanext-datitrentinoit/ckanext/datitrentinoit/templates/package/snippets/package_basic_fields.html', line 1 in top-level template code
  {% ckan_extends %}
File '/usr/local/data_loc/src/ckanext-dcatapit/ckanext/dcatapit/templates/package/snippets/package_basic_fields.html', line 7 in top-level template code
  {% set tmp=icustom_fields.append({'name': custom_field['name']}) %}
File '/usr/local/data_loc/src/ckan/ckan/templates/package/snippets/package_basic_fields.html', line 16 in top-level template code
  {% block package_basic_fields_custom %}{% endblock %}
File '/usr/local/data_loc/src/ckanext-dcatapit/ckanext/dcatapit/templates/package/snippets/package_basic_fields.html', line 92 in block "package_basic_fields_custom"
  {% snippet 'snippets/dcatapit_form_fields.html', data=data, errors=errors, schema_fields=pkg_fields %}
File '/usr/local/data_loc/src/ckan/ckan/lib/jinja_extensions.py', line 255 in _call
  return base.render_snippet(args[0], **kwargs)
File '/usr/local/data_loc/src/ckan/ckan/lib/base.py', line 79 in render_snippet
  renderer='snippet')
File '/usr/local/data_loc/src/ckan/ckan/lib/base.py', line 216 in render
  loader_class=loader_class)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
  return render_func()
File '/usr/local/data_loc/src/ckan/ckan/lib/base.py', line 154 in render_template
  return render_jinja2(template_name, globs)
File '/usr/local/data_loc/src/ckan/ckan/lib/base.py', line 104 in render_jinja2
  return template.render(**extra_vars)
File '/usr/local/app_loc/geosolutions/lib/python2.7/site-packages/jinja2/environment.py', line 894 in render
  return self.environment.handle_exception(exc_info, True)
File '/usr/local/data_loc/src/ckanext-dcatapit/ckanext/dcatapit/templates/snippets/dcatapit_form_fields.html', line 9 in top-level template code
  {{ dform.input(field.name,
File '/usr/local/data_loc/src/ckanext-dcatapit/ckanext/dcatapit/helpers.py', line 196 in format
  date = validate_dateformat(value, dateformat)
File '/usr/local/data_loc/src/ckanext-dcatapit/ckanext/dcatapit/helpers.py', line 208 in validate_dateformat
  date = datetime.datetime.strptime(date_string, date_format)
TypeError: must be string, not Undefined
