### ISSUE TITLE
ISPAT: dataset identifier

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-datitrentinoit#61]
At the moment the dcatapit `identifier` field is created using a generic uuid4 hash, and is recreated at every reharvesting.

The identifier stay the same, and should be in the form `IPA + ":" + UUID`, where the IPA for "Provincia di Trento" is `p_TN`.

The UUID could be generated using the `id` field from the source catalog.

**Comment by akshayb2022** [comment]
Hi @etj 
What I got from the task description is that I need to modify the identifier field , currently it is assigned a uuid4, and it changes on reharvesting. And I need to append IPA + " : " to uuid.
But could you please explain this `where the IPA for "Provincia di Trento" is p_TN`

**Comment by etj** [comment]
I guess you can just create a constant `DEFAULT_IPA = 'p_TN'` and use that since the IPA will not change for the datasets handled by this harvester.

**Comment by etj** [comment]
SInce the identifier format is quite free form (except for the prefix), I guess it's quite usless to create an hashcode from another identifier. It would more useful to keep the original identifier readable in the newly created one. 
In the new one we'll need
- IPA code
- original code
- info about the domain of the original code

--> <IPA>:<DOMAIN>_<ORIGINALID>
