### ISSUE TITLE
ISPAT: temporal extension

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-datitrentinoit#64]
The records in the ISPAT catalog may contain the fields `AnnoInizo` (starting year) and `AnnoFine` (ending year).
Those fields contain a year in a 4-digits format.

Such fields will be stored into the DCATAPIT fields called `temporal_start` and `temporal_end`, both with format `%d-%m-%Y`.

We need to modify the input values so that the starting year will be set at 1st Jan, and the ending year at 31st Dec.

So if 
- `AnnoInizio`=2013 
- `AnnoFIne`=2019, 
 
we'll have:
- `temporal_start` = 01-01-2013
- `temporal_end` = 31-12-2019

**Comment by etj** [comment]
The temporal extension, as defined in dcatapit, is an 0..* interval. 
It's encoded in an extra field with key `temporal_coverage` and as value a complex structure encoded as a json string.
Since the interval may be multiple, the outer structure is a list, with dict as elements. 
E.g.:
```json
[{"temporal_start": "2013-01-01", "temporal_end": "2019-12-31"}]
```

**Comment by etj** [comment]
Please note that :
- `temporal` [0..n]
  - `temporal_start` [1]
  - `temporal_end` [0..1]
 
This means that the `temporal` element shall be created only if there is a value for `AnnoInizio` (no default value here).
If `AnnoFine` is defined, we'll add also `temporal_end`, but there's not default there also.

**Comment by akshayb2022** [comment]
> For this `This means that the temporal element shall be created only if there is a value for AnnoInizio (no default value here).
If AnnoFine is defined, we'll add also temporal_end, but there's not default there also.`
If there is no value for `AnnoInizio` then do I need to to pass blank. And also if `AnnoFine` is not defined the `temporal_end` will be blank.

**Comment by etj** [comment]
@akshayb2022 
Example:
- No AnnoInizio, No AnnoFine --> NO 'temporal' field
- AnnoInizio=2013, No AnnoFine --> temporal = `[{'temporal_start': '2013-01-01'}]`
- AnnoInizio=2013, AnnoFine=2019 --> temporal = `[{'temporal_start': '2013-01-01', 'temporal_end':'2019-12-31'}]`
