### ISSUE TITLE
ISPAT: creator

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-datitrentinoit#65]
The `creator` field, (aka "Autore"), should be set the same for all the harvested datasets as: 
- name: "ISPAT Istituto di statistica della provincia di Trento"
- IPA code: XGT4IE
- mail: ispat@provincia.tn.it

**Comment by akshayb2022** [comment]
What are related schema fields for creator ?

**Comment by etj** [comment]
Field `creator`, it's a json-encoded list of dict in the format:
```json
[{
  "creator_identifier": IPA_CODE_OF_CREATOR,
  "creator_name": NAME_OF_CREATOR
}]
```

**Comment by etj** [comment]
Note that the population of the creator ("Author") fields in the harvester should be the equivalent of filling in the author fields in the dataset edit form.
You could try and:
- Edit a dataset (either a new one or an existing one)
- Check how that info is converted into DCAT by querying the .ttl encoding
   - TTL endpoint: http://YOURHOST/dataset/DATASETID.ttl"
   - Example: "http://ckan.geosolutionsgroup.com/dataset/persone-con-almeno-un-diploma-superiore-femmine.ttl"
- See how that info is shown to the user in the dataset page.
- You may also want to check how CKAN encodes that info
  -  Dataset query through API is in the form http://YOURHOST/api/3/action/package_show?id=DATASETID" 
  - Example "http://ckan.geosolutionsgroup.com/api/3/action/package_show?id=persone-con-almeno-un-diploma-superiore-femmine" 

Please check that once the harvester created a dataset, you can see the populated field in:
- The editing form
- The dataset show page
- The DCAT output
- The CKAN API output

**Comment by etj** [comment]
Field `creator`, it's a json-encoded list of dict in the format:
```json
[{
  "creator_identifier": IPA_CODE_OF_CREATOR,
  "creator_name": { 
       "it": NAME_OF_CREATOR_IN_ITALIAN, 
       "de": NAME_OF_CREATOR_IN_GERMAN, 
       "fr":..., 
       "en":...}
}]~

**Comment by etj** [comment]
Field `creator`, it's a json-encoded list of dict in the format:
```json
[{
  "creator_identifier": IPA_CODE_OF_CREATOR,
  "creator_name": { 
       "it": NAME_OF_CREATOR_IN_ITALIAN, 
       "de": NAME_OF_CREATOR_IN_GERMAN, 
       "fr":..., 
       "en":...}
}]~
