### ISSUE TITLE
ISPAT: contactPoint

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-datitrentinoit#66]
The `contactPoint` field, (aka "Contatto"), should be set the same for all the harvested datasets as: 
- name: "ISPAT Istituto di statistica della provincia di Trento"
- IPA code: XGT4IE
- mail: ispat@provincia.tn.it

**Comment by etj** [comment]
`contactPoint` is not in the dcatapit schema.
We should 
- define new fields in the schema
- de/serialize such fields in the dcat profile.

Example for schema customization [here](https://github.com/geosolutions-it/ckanext-umbria/blob/11ed6b3be0b7cd267dcdd3fae8b144119e7910a8/ckanext/umbria/plugin.py#L49-L85)
Example for profile customization [here](https://github.com/geosolutions-it/ckanext-umbria/blob/11ed6b3be0b7cd267dcdd3fae8b144119e7910a8/ckanext/umbria/profile.py#L21-L26)
Example for profile customization declaration [here](
https://github.com/geosolutions-it/ckanext-umbria/blob/11ed6b3be0b7cd267dcdd3fae8b144119e7910a8/setup.py#L87-L88)
Example for profile configuration [here](
https://github.com/geosolutions-it/ckanext-umbria/blob/11ed6b3be0b7cd267dcdd3fae8b144119e7910a8/README.md?plain=1#L30-L35)

**Comment by akshayb2022** [comment]
> The `contactPoint` field, (aka "Contatto"), should be set the same for all the harvested datasets as:
> 
> * name: "ISPAT Istituto di statistica della provincia di Trento"
> * IPA code: XGT4IE
> * mail: [ispat@provincia.tn.it](mailto:ispat@provincia.tn.it)

Hi @etj 
what I got from the task is that,  
We have all schema in this file `https://github.com/geosolutions-it/ckanext-dcatapit/blob/master/ckanext/dcatapit/schema.py`. And this file belongs to this repo `https://github.com/geosolutions-it/ckanext-dcatapit`
I need to add the fields in schema in this file `https://github.com/geosolutions-it/ckanext-dcatapit/blob/master/ckanext/dcatapit/schema.py`.
And I need to push these changes on this repo https://github.com/geosolutions-it/ckanext-dcatapit.
Then I need to push the other changes on this repo `https://github.com/geosolutions-it/ckanext-datitrentinoit`
Please correct me if I'm wrong.

**Comment by etj** [comment]
@akshayb2022 nope :)

The contactPoint requirement is for ckanext-datitrentino only.
If you modify ckanext-dcatapit those changes will be used also by other ppl using the dcatapit extension.

In my previous comment there are links to another project that is customizing the dcatapit schema, without changing the the code in dcatapit.
